<<<<<<< HEAD
# We may add certain file to ignore in the codecov coverage report
ignore:
=======
ignore:
  - core/src/main/scala/com/databricks/labs/remorph/parsers/FunctionBuilder.scala
>>>>>>> 80828ca7 (Rework functions to remove overly explicit definitions in the grammar (#345))
